"""Add soft delete fields to alumnos

Revision ID: 53ea819ab516
Revises: a1828ef24055
Create Date: 2026-07-31 16:37:54.696410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ea819ab516'
down_revision = 'a1828ef24055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('fecha_eliminacion')
        batch_op.drop_column('eliminado')

    # ### end Alembic commands ###
