"""add alumno foto

Revision ID: 57789df0236e
Revises: c77ca1793d47
Create Date: 2026-09-03 10:10:07.388102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57789df0236e'
down_revision = 'c77ca1793d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
