"""Add indexes for frequently queried columns

Revision ID: a1828ef24055
Revises: 
Create Date: 2026-07-31 16:37:21.995979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1828ef24055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alumnos_carrera_id'), ['carrera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumnos_fecha_registro'), ['fecha_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumnos_institucion_id'), ['institucion_id'], unique=False)

    with op.batch_alter_table('auditorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditorias_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditorias_usuario_id'))

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alumnos_institucion_id'))
        batch_op.drop_index(batch_op.f('ix_alumnos_fecha_registro'))
        batch_op.drop_index(batch_op.f('ix_alumnos_carrera_id'))

    # ### end Alembic commands ###
