"""partial unique index for active usuarios

Revision ID: c77ca1793d47
Revises: d343106d38f0
Create Date: 2026-08-31 00:04:16.380511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77ca1793d47'
down_revision = 'd343106d38f0'
branch_labels = None
depends_on = None


def _existing_names():
    bind = op.get_bind()
    insp = sa.inspect(bind)
    idx = {ix['name'] for ix in insp.get_indexes('usuarios')}
    uq = {c['name'] for c in insp.get_unique_constraints('usuarios')}
    return idx | uq


def upgrade():
    # Drops/creates defensivos: en prod el esquema puede no tener
    # exactamente los mismos nombres (ej. usuarios_email_key nunca
    # existió allá) y MySQL no soporta DROP IF EXISTS. Sin esto,
    # `flask db upgrade` muere con OperationalError 1091.
    existing = _existing_names()
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        if 'usuarios_email_key' in existing:
            batch_op.drop_constraint('usuarios_email_key', type_='unique')
        if 'ix_usuarios_dni' in existing:
            batch_op.drop_index('ix_usuarios_dni')
        if 'ix_usuarios_username' in existing:
            batch_op.drop_index('ix_usuarios_username')

    existing = _existing_names()
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        if 'ix_usuarios_dni' not in existing:
            batch_op.create_index('ix_usuarios_dni', ['dni'], unique=False)
        if 'ix_usuarios_username' not in existing:
            batch_op.create_index('ix_usuarios_username', ['username'], unique=False)
        if 'uq_usuarios_dni_activo' not in existing:
            batch_op.create_index('uq_usuarios_dni_activo', ['dni'], unique=True, postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        if 'uq_usuarios_email_activo' not in existing:
            batch_op.create_index('uq_usuarios_email_activo', ['email'], unique=True, postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        if 'uq_usuarios_username_activo' not in existing:
            batch_op.create_index('uq_usuarios_username_activo', ['username'], unique=True, postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('uq_usuarios_username_activo', postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        batch_op.drop_index('uq_usuarios_email_activo', postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        batch_op.drop_index('uq_usuarios_dni_activo', postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)
        batch_op.drop_index(batch_op.f('ix_usuarios_dni'))
        batch_op.create_index(batch_op.f('ix_usuarios_dni'), ['dni'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('usuarios_email_key'), ['email'])

    # ### end Alembic commands ###
