"""partial unique index for active usuarios

Revision ID: c77ca1793d47
Revises: d343106d38f0
Create Date: 2026-08-31 00:04:16.380511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77ca1793d47'
down_revision = 'd343106d38f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_email_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_usuarios_dni'))
        batch_op.create_index(batch_op.f('ix_usuarios_dni'), ['dni'], unique=False)
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=False)
        batch_op.create_index('uq_usuarios_dni_activo', ['dni'], unique=True, postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        batch_op.create_index('uq_usuarios_email_activo', ['email'], unique=True, postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        batch_op.create_index('uq_usuarios_username_activo', ['username'], unique=True, postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('uq_usuarios_username_activo', postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        batch_op.drop_index('uq_usuarios_email_activo', postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        batch_op.drop_index('uq_usuarios_dni_activo', postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)
        batch_op.drop_index(batch_op.f('ix_usuarios_dni'))
        batch_op.create_index(batch_op.f('ix_usuarios_dni'), ['dni'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('usuarios_email_key'), ['email'])

    # ### end Alembic commands ###
