"""password recovery single-use and rate limit

Revision ID: d343106d38f0
Revises: c7e1a92f4b30
Create Date: 2026-08-30 22:53:57.688586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd343106d38f0'
down_revision = 'c7e1a92f4b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # password_reset_tokens + password_reset_attempts (single-use 15min + rate limit 3/15)
    # Tablas ya existen en dev via create_all; en prod (INIT_DB_ON_START=False) deben crearse via migrate.
    # Usamos batch + check via inspector no disponible en offline, por lo que creamos si no existe
    # via try/except y creacion idempotente.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing = inspector.get_table_names()

    if 'password_reset_tokens' not in existing:
        op.create_table('password_reset_tokens',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('usuario_id', sa.Integer(), nullable=False),
            sa.Column('token_hash', sa.String(length=128), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('used_at', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_password_reset_tokens_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=False)
            batch_op.create_index(batch_op.f('ix_password_reset_tokens_usuario_id'), ['usuario_id'], unique=False)

    if 'password_reset_attempts' not in existing:
        op.create_table('password_reset_attempts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('ip_address', sa.String(length=45), nullable=True),
            sa.Column('username', sa.String(length=50), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('password_reset_attempts', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_password_reset_attempts_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_password_reset_attempts_ip_address'), ['ip_address'], unique=False)
            batch_op.create_index(batch_op.f('ix_password_reset_attempts_username'), ['username'], unique=False)

    # Fix visitas.promotor_id nullable ya reflejado en modelo pero no en DB antigua
    if 'visitas' in existing:
        cols = {c['name']: c for c in inspector.get_columns('visitas')}
        if 'promotor_id' in cols and not cols['promotor_id']['nullable']:
            with op.batch_alter_table('visitas', schema=None) as batch_op:
                batch_op.alter_column('promotor_id',
                       existing_type=sa.INTEGER(),
                       nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.alter_column('promotor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('password_reset_attempts')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
