"""allow reuse dni for alumnos after soft delete

Revision ID: d3c1cfee4e8e
Revises: 57789df0236e
Create Date: 2026-09-03 11:00:21.648736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c1cfee4e8e'
down_revision = '57789df0236e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alumnos_dni'))
        batch_op.create_index(batch_op.f('ix_alumnos_dni'), ['dni'], unique=False)
        batch_op.create_index('uq_alumnos_dni_activo', ['dni'], unique=True, postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_index('uq_alumnos_dni_activo', postgresql_where=sa.text('eliminado = false'), sqlite_where=sa.text('eliminado = 0'))
        batch_op.drop_index(batch_op.f('ix_alumnos_dni'))
        batch_op.create_index(batch_op.f('ix_alumnos_dni'), ['dni'], unique=True)

    # ### end Alembic commands ###
