# -*- coding: utf-8 -*-
"""Interfaces de repositorios - descritas como protocolos."""
from typing import Protocol, Optional, List

class AlumnoRepository(Protocol):
    def find_by_dni(self, dni: str): ...
    def find_by_id(self, alumno_id: int): ...
    def list_active(self): ...
    def save(self, alumno): ...
    def find_with_filters(self, **filters): ...

class VisitaRepository(Protocol):
    def save(self, visita): ...
    def find_by_alumno(self, alumno_id: int): ...
