from app.modules.identidad.domain.usuario import Usuario
from app.modules.identidad.domain.rol import Rol
from app.modules.registro.domain.alumno import Alumno
from app.modules.registro.domain.institucion_educativa import InstitucionEducativa
from app.modules.registro.domain.visita import Visita
from app.modules.registro.domain.promotor import Promotor
from app.modules.auditoria.domain.auditoria import Auditoria
from app.modules.identidad.domain.sesion import Sesion
from app.modules.registro.domain.carrera import Carrera
from app.models.reporte import Reporte
from app.models.dashboard_estadistica import DashboardEstadistica
