from app.models.usuario import Usuario
from app.models.rol import Rol
from app.models.alumno import Alumno
from app.models.institucion_educativa import InstitucionEducativa
from app.models.visita import Visita
from app.models.promotor import Promotor
from app.models.auditoria import Auditoria
from app.models.sesion import Sesion
from app.models.carrera import Carrera
from app.models.reporte import Reporte
from app.models.dashboard_estadistica import DashboardEstadistica
